// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4UTcdw02VeD0w33Zh2q_yyGva9jO_OWI',
    appId: '1:924645965609:web:74888590f5354eb2524138',
    messagingSenderId: '924645965609',
    projectId: 'cmsc23-final-project-a2cc4',
    authDomain: 'cmsc23-final-project-a2cc4.firebaseapp.com',
    storageBucket: 'cmsc23-final-project-a2cc4.appspot.com',
    measurementId: 'G-B2PWFH2QJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzVRMhwrKCtEsGShvMK16aNd1bX3Htk2Y',
    appId: '1:924645965609:android:9b6f32d909332fcc524138',
    messagingSenderId: '924645965609',
    projectId: 'cmsc23-final-project-a2cc4',
    storageBucket: 'cmsc23-final-project-a2cc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNHurvC8h1N0m1YiL1i1Vwmr8O1kR5pkk',
    appId: '1:924645965609:ios:6733eda0c4a8cb78524138',
    messagingSenderId: '924645965609',
    projectId: 'cmsc23-final-project-a2cc4',
    storageBucket: 'cmsc23-final-project-a2cc4.appspot.com',
    iosClientId: '924645965609-0l1nkn6cap2bhn4806ru5qojmp1ul85q.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProjectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNHurvC8h1N0m1YiL1i1Vwmr8O1kR5pkk',
    appId: '1:924645965609:ios:7f62cc1eb700369c524138',
    messagingSenderId: '924645965609',
    projectId: 'cmsc23-final-project-a2cc4',
    storageBucket: 'cmsc23-final-project-a2cc4.appspot.com',
    iosClientId: '924645965609-uf58a29o30pqhk9u5fr0mo24cfmciliu.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProjectApp.RunnerTests',
  );
}
